# Generated by Django 4.1.5 on 2023-04-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0002_node_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='url',
            field=models.URLField(default='/'),
        ),
    ]
