# Generated by Django 4.1.5 on 2023-04-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0003_alter_node_parent_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='node',
            name='parent_node',
        ),
        migrations.AddField(
            model_name='menu',
            name='root_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree_menu.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='children',
            field=models.ManyToManyField(blank=True, to='tree_menu.node'),
        ),
    ]
