# Generated by Django 4.1.5 on 2023-04-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0004_node_related_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='symbol',
            field=models.CharField(choices=[('└', '└'), ('├', '├'), ('─', '─'), ('│', '│')], default='└', max_length=1),
        ),
    ]
